# Tugas Hari PERTAMA_PYTHON INTRODUCTION

<h2>Soal 1: Hello World to Python</h2>
    
Print Say Hello World to Python

In [1]:
print("Hello World  Python")

Hello World  Python


Expected Output : 

Hello World Python

<h2>Soal 2: Aritmatika di Python </h2>
    
- Buat statement pertambahan antara 2 number di Python
- Buat statement perkurangan antara 2 number di Python
- Buat statement perkalian antara 2 number di Python
- Buat statement pembagian antara 2 number di Python

In [2]:
#Pertambahan
3+6

9

In [3]:
#Perkurangan
3-6

-3

In [4]:
#Perkalian
3*6

18

In [5]:
#Pembagian
3/6

0.5

<h2>Quiz 3: Assign Variable dan Tipe Data Integer, Float </h2>

- Buat suatu variabel a dan b, dimana a dan b adalah nilai bertipe data numeric
- Berikan suatu nilai bertipe data integer, hasil pembagian dari a dengan b
- Berikan suatu nilai bertipe data float, hasil pembagian dari a dengan b

In [6]:
a=23
b=3

print("Hasil pembagian dengan tipe data integer =", a//b)
print("Hasil pembagian dengan tipe data float =",a/b)

Hasil pembagian dengan tipe data integer = 7
Hasil pembagian dengan tipe data float = 7.666666666666667


<h2>Soal 4: String Operation </h2>

- masukan nama depan kamu kedalam suatu variable firstname
- masukan nama belakang kamu kedalam suatu variable lasname
- tampilkan suatu kalimat 'Hello sanbercode, saya firstname lastname! saya siap belajar python data science.'

In [7]:
firstname = 'Ria Puan'
lastname = 'Adhitama'

print ('Hello sanbercode, saya', firstname,lastname, '! saya siap belajar python data science.')

Hello sanbercode, saya Ria Puan Adhitama ! saya siap belajar python data science.


Expected Output :

Hello sanbercode, saya fauzan taufik! saya siap belajar python data science.

<h2>Soal 5: Tipe Data</h2>

Lengkapi code di bawah ini untuk menghasilkan output yang sesuai

In [8]:
p = 9.99999
q = 'the number: '
print(q + str (p))

the number: 9.99999


Expected Output :

the number: 9.99999

# Tugas Hari KEDUA_DATA STRUCTURE

# Data Structure

<h2>Soal 1: Perbedaan Data Structure</h2>

Jawab Pertanyaan di bawah ini:

Jelaskan perbedaan dari List, Tuple, Set dan Dictionary!

List merupakan tipe data berurut yang anggotanya dapat berasal dari berbagai tipe data, cara membuatnya dengan diawali dan diakhiri tanda kurung siku.
Tuple sama seperti string dan list, merupakan anggota tipe data berurut, cara membuatnya dengan menggunakan kurung biasa atau tanpa tanda kurung.
Set. satu-satunya anggota tipe data tak berurut dikarenakan set tidak mengenal indeks, membuat posisi tiap anggotanya tak jelas. Selain itu set punya sifat anggota yang unik artinya anggota satu dan yang lain tidak akan ada yang sama. Jika ada yang sama (duplikasi) maka akan dihapus salah satu. Cara membuatnya dengan menggunakan kurung kurawal.
Dictionary. tipe data yang cara membuatnya sama seperti set membutuhkan tanda kurung kurawal, bedanya dalam dictionary anggotanya tersusun atas dua atribut key dan value yang keduanya ini dipisahkan denga tanda titik dua (key:value). Key dapat bertindak sebagai indeks jadi nilainya harus bersifat unik.

List, Set dan Dictionary merupakan tipe data yang bersifat mutable. Khusus untuk set karena ia tidak mengenal indeks maka untuk mengubah isi di dalamnya membutuhkan sebuah fungsi.

---



---



# List

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
print(a[1][1], a[1][2])

0 6


Expected Output :


[0, 6]

In [ ]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
hasil = [a, c, b]
print(hasil)

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


<h2>Soal 4: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
a[1][0] = 11

print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

In [ ]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
hasil = b + a
print(hasil)

[5, 1, 3, 1, 3, 5]


<h2>Soal 5: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del(areas[8:10])

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 6: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [ ]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [i for i in S if i%2==0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]



---



---



# Tuple

## Soal 7. Mengakses Tuple

Gunakan cara sclicing untuk mengakses tuple sehingga mendapatkan hasil sesuai expected output

In [ ]:
tuple_1 = (1, 2, 6, 7, 8, 9, 10)

#akses tuple
print(tuple_1[2:5])

(6, 7, 8)


Expected Outpout:


(6, 7, 8)



---



---



# Dictionary

<h2>Soal 8: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe ['itali'] = 'roma'

# cek apakah itali ada di dalam objek dictionary
print('itali' in europe)

True


Expected Output:
    
True

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print('dict_keys', (['spain','france','germany', 'norway']))
# print nilai dari key franche
print(europe['france'])

dict_keys ['spain', 'france', 'germany', 'norway']
paris


<h2>Soal 9: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe ['germany'] = 'berlin'

# remove australia dari europa
europe.pop ('australia')

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 10: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country1 = {'indonesia' : {'capital':'jakarta', 'population':250}}
country.update(country1)

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 11: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for i, j in country.items():
    print('Ibukota '+ i +' adalah ' + j ['capital'])

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta



---



---



# Set

## Soal 12: Remove Duplicate using set


Hilangkan nilai duplikat dari sebuah objek list dengan menggunakan cara set sehingga menjadi sebuah tipe set

In [ ]:
obj_list = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 9, 10]

#using set
obj_list.remove(9)
print(obj_list)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


Expected output: 

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## Soal 13: Mengubah dan menghapus anggota set

Ubahlah dan hapus anggota set sehingga mendapatkan hasil yang diinginkan


In [ ]:
set_1 = {1, 2, 3, 4, 5}

#tambahkan anggota set dengan nilai {6,7,8}
set_1.update([6,7,8])
#hapus nilai anggota set 8
set_1.discard(8)

print(set_1)

{1, 2, 3, 4, 5, 6, 7}


Expected output:

{1, 2, 3, 4, 5, 6, 7}

## Soal 14: Operasi pada Set

Carilah irisan dari ke dua set dengan menggunakan metode intersection

In [ ]:
set_2 = {6, 8, 9, 10, 24}
set_3 = {6, 10, 8, 25, 13}

#intersection set
print(set_3.intersection(set_2))

{8, 10, 6}


Expected output:


{6, 8, 10}

Built in Function

In [ ]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p, reverse=False))
# get max value of list
print(max(p))

[0, 2, 4, 5, 9, 10]
10


# Tugas hari KETIGA_FUNCTION AND METHOD

<h2>Soal 1: Helper Function</h2>

Jawab Pertanyaan di bawah ini:

Misalkan kamu ingin mengetahui tentang kegunaan fungsi 'len' di Python, maka fungsi apa yang bisa kamu gunakan untuk menolong kamu?

In [ ]:
# lengkapi code ini
print(help(len))

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

None


<h2>Soal 2: Built-in Function</h2>

Jawab Pertanyaan di bawah ini:
    
Apa itu built-in Function?

Sebutkan 3 built-in Function di pyhon!

Berikan contoh masing2 1 cara penggunaan built-in function yang kamu sebutkan sebelumnya

//isi jawaban text disini
Built-in function dalam python merupakaan fungsi bawaan yang ada di python atau fungsi yang dibangun oleh python yang digunakan untuk melakukan berbagai hal.
Contoh built-in function di python :
    1. bin() , yaitu fungsi yang digunakan untuk mengubah integer menjadi string biner.
    2. round(), yaitu fungsi yang digunakan untuk membulatkan bilangan yang berkoma.
    3. float(), yaitu fungsi yang digunakan untuk mengembalikan bilangan float dari bilangan atau string.

In [ ]:
# Contoh Penggunaan Built-in Function

#1. Contoh Penggunaan Fungsi bin ()
angka = 2506
print('Nilai biner dari 2506 yaitu', bin(angka))

#2. Contoh Penggunaan Fungsi round ()
x =round (1.68, 1)
print('Didapatkan nilai : ', x)

#3. Contoh Penggunaan Fungsi sloat ()
p = 15
q = 3
Hasil = p/q
print('Diperoleh nilai : ', float(Hasil))


Nilai biner dari 2506 yaitu 0b100111001010
Didapatkan nilai :  1.7
Diperoleh nilai :  5.0


<h2>Soal 3: Method dan Function</h2>

Jawab Pertanyaan di bawah ini:
    
- Apa perbedaan method dan function?

Function itu independen yang berarti tidak terikat dengan suatu objek, dimana saat kita membuat suatu fungsi kita tidak perlu mengikat suatu objek. Function bersifat explisit dan tidak berurusan dengan Python Class.
Sedangkan method bersifat dependen yang berarti terasosiasi dengan suatu objek (merupakan fungsi dari suatu objek), bersifat implisit, dan bisa beroperasi dengan Python Class.

<h2>Soal 4: Menggunkan Method String</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
kalimat = "Corona cepat selesai"

# gunakan method untuk mengubah nilai kalimat menjadi uppercase semua kemudian tampilkan hasilnya
print(kalimat.upper())

# gunakan method untuk menghitung berapa huruf e di dalam kalimat
print(kalimat.count("e"))

CORONA CEPAT SELESAI
3


Expected Output:

CORONA CEPAT SELESAI

3

<h2>Soal 5: Membuat Simple Function</h2>

Buatlah suatu fungsi yang menerima satu input argumen berbentuk list dan mempunyai elemen bertipe numeric semua, dimana fungsi tersebut berguna untuk menghitung rata2 dari kumpulan elemen list tersebut. namai fungsi tersebut 'mean_list'

In [ ]:
obj_list = [11.25, 18.0, 20.0, 10.75, 9.50]
def mean_list(inp_list):
    jumlah=sum(inp_list)
    bagi=len(inp_list)
    return jumlah/bagi
    
print(mean_list(obj_list))

13.9


Expected Output:

13.9

<h2>Soal 6: Membuat Function dengan Multiple arguments</h2>

Buatlah suatu fungsi untuk melakukan penggabungan antara dua list

In [ ]:
obj_list = [2, 4, 5, 6]
obj_penambah = [1, 2, 3]

def kali_list(obj_list, obj_penambahan):
    # isikan kode
    total = (obj_list + obj_penambahan)
    return total
    
    
print(kali_list(obj_list, obj_penambah))

[2, 4, 5, 6, 1, 2, 3]


Expected Output:

[2, 4, 5, 6, 1, 2, 3]

# Tugas hari KEEMPAT_LOGIC CONTROL FLOW & LOOPING

<h2>Soal 1: Comparison Operator</h2>

- Berikan contoh comparison dari tipe data string
- Berikan contoh comparison dari tipe data boolean
- Berikan contoh comparison dari tipe data integer

In [ ]:
#Contoh Comparison dari tipe data string

print('"Itu" dengan "itu" apakah sama?', 'itu' == 'itu')

#Contoh Comparison dari tipe data boolean

print ('"False" dengan "False" apakah sama?', False == False)

#Contoh Comparison dari tipe data integer

print('Benarkah nilai 3 samadengan 9?', 3 == 9)

"Itu" dengan "itu" apakah sama? True
"False" dengan "False" apakah sama? True
Benarkah nilai 3 samadengan 9? False


<h2>Soal 2: Boolean Comparison</h2>

- Berikan contoh gabungan multiple comparison menggunkan Boolean Comparisin 'and'
- Berikan contoh gabungan multiple comparison menggunkan Boolean Comparisin 'or'
- Berikan contoh gabungan multiple comparison menggunkan Boolean Comparisin 'not'

In [ ]:
#Boolean Comparison and

def kehadiran(nama,NIM):
    if nama=='Benar' and NIM=='Benar':
        print('Kahadiran dianggap Masuk')
    else :
        print('Kehadiran dianggap Tidak Masuk')
        
        
#Boolean Comparison or

def kriteria(Perempuan, Jurusan_Matematika) :
    if Perempuan=='Benar' or Jurusan_Matematika=='Benar' :
        print('Kriteria Terpenuhi')
    else :
        print('Kriteria Tidak Terpenuhi')
        

#Boolean Comparison not

a=15
if(not a) :
    print('Benar')
else :
    print('Salah')

Salah


<h2>Soal 3: If-Else Statement</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

- Bualah sebuah if-else statement yang dimana akan mem-print 'Besar' jika ruangan adalah 'Kamar' dan ukuran lebih dari 12, kemudian mem-print 'Sedang' jika ruangan adalah 'Kamar' dan ukuran lebih dari 6 dan memprint 'Kecil' jika ruangan adalah 'Kamar' dan ukuran ruangan lebih kecil dan sama dengan 6.

In [ ]:
ruangan = 'Kamar'
size = 20

if ruangan == 'Kamar' and size>=12 :
    print('Besar')
elif ruanggan == 'Kamar' and size>=6 :
    print('Sedang')
elif ruangan == 'Kamar' and size <=6 :
    print('Kecil')
else :
    print('-')

Besar


<h2>Soal 4: Comparison Operator dengan fungsi</h2>

Buatlah sebuah fungsi yang menerima satu argument bertipe data numeric dan menghasilkan sebuah return sebagai berikut :
- menghasilkan return 'Aneh' jika nilai dari argument tersebut adalah bilangan ganjil
- menghasilkan return 'Tidak Aneh' jika nilai dari argument tersebut adalah bilangan genap dan diantara nilai 2 sampai 5 (2 dan 5 termasuk)
- menghasilkan return 'Aneh' jika nilai dari argument tersebut adalah bilangan genap dan diantara nilai 6 sampai 20 (6 dan 20 termasuk)
- menghasilkan return 'Tidak Aneh' jika nilai dari argument tersebut adalah bilangan genap dan lebih besari dari 20

In [ ]:
# Buat fungsi

def Weirdnumb(x) :
    if x % 2!=0 :
            print('Aneh')
    elif (x % 2==0) and (2<=x>=5) :
            print('Tidak Aneh')
    elif (x % 2==0) and (6<=x>=20) :
            print('Aneh')
    elif (x % 2==0) and (x>20) :
            print('Tidak Aneh')
            
print(Weirdnumb(8))

Tidak Aneh
None


<h2>Soal 5: While Loop dan For Loop</h2>

- Apa perbedaan while loop dan for loop?
- Berikan contoh sederhana cara menggunakan while loop dan for loop

In [ ]:
#For loop (perulangan yang terhitung), biasanya digunakan untuk mengulangi kode yang sudah diketahui banyaknya perulangan. 
#Sedangkan while loop (perulangan yang tidak terhitung), biasanya digunakan untuk perulangan yang memiliki syarat dan tidak tentu berapa banyak perulangannya.

# Tulis Kode

#While Loop
i = 0
while i<10 :
    print(i, end='')
    i+=1
    
#For Loop
for i in range(10) :
    print(i, end='')

01234567890123456789

<h2>Soal 6: While Loop</h2>
    
Buatlah sebuah code while loop sebagai berikut :
- Buatlah suatu fungsi yang merima satu input nilai numeric
- Dalam fungsi, Buat sebuah while-loop dengan melakukan comparasi terhadap inputan tersebut, dimana looping/iterasi terus berjalan apabila nilai inputan tidak sama dengan 0
- Dalam setiap iterasi update nilai variable inputan itu, jika input lebih dari 0, maka kurangi variabel tersebut sebesar 1, selain itu tambahkan 1
- print nilai variable input dalam setiap awal iterasi

In [ ]:
a = 10

def fungsi_while(a):
        while a !=0:
            print(a)
            if a>0 :
                a=a-1
            else :
                a=a+1

fungsi_while(a)

10
9
8
7
6
5
4
3
2
1


Expected Output:

10

9

8

7

6

5

4

3

2

1

<h2>Soal 7: For Loop</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan:

- Buatlah sebuah loop dengan mengiterasi sebuah objek list kemudian di kalikan dengan index dari list tersebut dan print hasilnya

In [ ]:
obj_list= [1, 16, 11, 10, 5]

# lengkapi code di bawah
for i, angka in enumerate(obj_list):
        print(i * angka)


0
16
22
30
20


Expected Output:

0

16

22

30

20


# Tugas hari KEEMPAT_LOGIC CONTROL FLOW & LOOPING

# Soal 1: Law of Large Numbers

Menurut Law of Large Numbers (LLN) jika kita mengulang suatu percobaan, semakin banyak kita mengulang maka rata-rata hasil yang di dapat akan mendekati apa yang kita perkirakan.

![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/e8dff3831b1e5b6f0e187c733583ab8d02574363)

Sebagai caontoh, sebuah dadu dengan 6-sisi akan menghasilkan angka 1, 2, 3, 4, 5, atau 6 dengan probabilitas yang sama untuk masing-masing angkanya. Maka, perkiraan rata-rata hasil yang akan di dapat adalah (1+2+3+4+5+6)/6 = 3.5
Menurut LLN, semakin banyak kita mengocok dadu, maka rata-rata hasil yang didapatkan akan semakin mendekati nilai perkiraan rata-ratanya yaitu 3.5

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Lawoflargenumbers.svg/400px-Lawoflargenumbers.svg.png)

Begitu juga jika kita memiliki sebuah dataset berisi angka-angka acak dengan nilai rata-rata(μ) = 0 dan standar deviasi(σ) = 1, maka angka-angka tersebut akan terdistribusi secara normal dengan semakin banyaknya isi dari dataset tersebut.

![alt text](https://img.favpng.com/9/9/7/standard-deviation-normal-distribution-mean-statistics-png-favpng-5cX7qC8aqmp0pQthmW3nSVj9a.jpg)

Dari gambar di atas, maka semakin banyaknya isi dari dataset, jumlah angka-angka pada dataset yang memiliki nilai -1 < angka < 1 akan semakin mendekati 68.2%.
Lengkapi code dibawah ini untuk membuktikan hal tersebut.


In [ ]:
import numpy as np
from numpy.random import randn

N = 1000                      #Tentukan ukuran sampel
counter = 0                 #Untuk mereset perhitungan

for i in randn (N):               #Mulai iterasi dan tambahkan nilai counter jika memenuhi syarat
    if (-1 <= i<= 1):
        counter = counter + 1


hasil = counter/N           #Hitung nilai persentase jumlahnya
print(hasil)

0.69


---

# Soal 2: Menghitung nilai-nilai dari statistika deskriptif

In [ ]:
import statistics
import numpy as np
import scipy.stats

#Berikut adalah data dari breast cancer dataset, area dan status mematikan atau tidaknya

area = [1001. , 1326. , 1203. ,  386.1, 1297. ,  477.1, 1040. ,  577.9, 519.8,  475.9,  797.8,  781. , 1123. ,  782.7,  578.3,  658.8, 684.5,  798.8, 1260. ,  566.3,  520. ,  273.9,  704.4, 1404. ,
        904.6,  912.7,  644.8, 1094. ,  732.4,  955.1, 1088. ,  440.6, 899.3, 1162. ,  807.2,  869.5,  633. ,  523.8,  698.8,  559.2, 563. ,  371.1, 1104. ,  545.2,  531.5, 1076. ,  201.9,  534.6,
        449.3,  561. ,  427.9,  571.8,  437.6, 1033. ,  712.8,  409. , 1152. ,  656.9,  527.2,  224.5,  311.9,  221.8,  645.7,  260.9, 499. ,  668.3,  269.4,  394.1,  250.5,  502.5, 1130. ,  244. ,
        929.4,  584.1,  470.9,  817.7,  559.2, 1006. , 1245. ,  506.3, 401.5,  520. , 1878. , 1132. ,  443.3, 1075. ,  648.2, 1076. , 466.1,  651.9,  662.7,  728.2,  551.7,  555.1,  705.6, 1264. ,
        451.1,  294.5,  412.6,  642.5,  582.7,  143.5,  458.7,  298.3, 336.1,  530.2,  412.5,  466.7, 1509. ,  396.5,  290.2,  480.4, 629.9,  334.2,  230.9,  438.6,  245.2,  682.5,  782.6,  982. ,
        403.3, 1077. , 1761. ,  640.7,  553.5,  588.7,  572.6, 1138. , 674.5, 1192. ,  455.8,  748.9,  809.8,  761.7, 1075. ,  506.3, 423.6,  399.8,  678.1,  384.8,  288.5,  813. ,  398. ,  512.2,
        355.3,  432.8,  432. ,  689.5,  640.1,  585. ,  519.4,  203.9, 300.2,  381.9,  538.9,  460.3,  963.7,  880.2,  448.6,  366.8, 419.8, 1157. , 1214. ,  464.5, 1686. ,  690.2,  357.6,  886.3,
        984.6,  685.9,  464.1,  565.4,  736.9,  372.7,  349.6,  227.2, 302.4,  832.9,  526.4,  508.8, 2250. , 1311. ,  766.6,  402. , 710.6,  317.5, 1041. ,  420.3,  428.9,  463.7,  609.9,  507.4,
        288.1,  477.4,  671.4,  516.4,  588.9, 1024. , 1148. ,  642.7, 461. ,  951.6, 1685. ,  597.8,  481.9,  716.6,  295.4,  904.3, 529.4,  725.5, 1290. ,  428. , 2499. ,  948. ,  610.7,  578.9,
        432.2,  321.2, 1230. , 1223. ,  568.9,  561.3,  313.1,  761.3, 546.4,  641.2,  329.6,  684.5,  496.4,  503.2,  895. ,  395.7, 386.8, 1319. ,  279.6,  603.4, 1670. , 1306. ,  623.9,  920.6,
        575.3,  476.5,  389.4,  590. , 1155. ,  337.7,  541.6,  512.2, 347. ,  406.3, 1364. ,  407.4, 1206. ,  928.2, 1169. ,  602.4, 1207. ,  713.3,  773.5,  744.9, 1288. ,  933.1,  947.8,  758.6,
        928.3, 1419. ,  346.4,  561. ,  512.2,  344.9,  632.6,  388. , 1491. ,  289.9,  998.9,  435.6,  396.6, 1102. ,  572.3,  587.4, 1138. ,  427.3, 1145. ,  805.1,  516.6,  489. ,  441. ,  515.9,
        394.1,  396. ,  651. ,  687.3,  513.7,  432.7,  492.1,  582.7, 363.7,  431.1,  633.1,  334.2, 1217. ,  471.3, 1247. ,  334.3, 403.1,  417.2,  537.3,  246.3,  566.2,  530.6,  418.7,  664.9,
        504.1,  409.1,  221.2,  481.6,  461.4, 1027. ,  244.5,  477.3, 324.2, 1274. ,  504.8, 1264. ,  457.9,  489.9,  616.5,  446. , 813.7,  826.8,  793.2,  514. ,  387.3,  390. ,  464.4,  918.6,
        514.3, 1092. ,  310.8, 1747. ,  641.2,  280.5,  373.9, 1194. , 420.3,  321.6,  445.3,  668.7,  402.7,  426.7,  421. ,  758.6, 2010. ,  716.6,  384.6,  485.8,  512. ,  593.7,  241. ,  278.6,
        491.9,  546.1,  496.6,  838.1,  552.4, 1293. , 1234. ,  458.4, 1546. , 1482. ,  840.4,  711.8, 1386. , 1335. ,  579.1,  788.5, 338.3,  562.1,  580.6,  361.6,  386.3,  372.7,  447.8,  462.9,
        541.8,  664.7,  462. ,  596.6,  392. , 1174. ,  321.6,  234.3, 744.7, 1407. ,  446.2,  609.1,  558.1,  508.3,  378.2,  431.9, 994. ,  442.7,  525.2,  507.6,  469.1,  370. ,  800. ,  514.5,
        991.7,  466.1,  399.8,  373.2,  268.8,  693.7,  719.5,  433.8, 271.2,  803.1,  495. ,  380.3,  409.7,  656.1,  408.2,  575.3, 289.7,  307.3,  333.6,  359.9,  381.1,  501.3,  685. ,  467.8,
       1250. , 1110. ,  673.7,  599.5,  509.2,  611.2,  592.6,  606.5, 371.5,  928.8,  585.9,  340.9,  990. ,  441.3,  981.6,  674.8, 659.7, 1384. ,  432. , 1191. ,  442.5,  644.2,  492.9,  557.2,
        415.1,  537.9,  520.2,  290.9,  930.9, 2501. ,  646.1,  412.7, 537.3,  542.9,  536.9,  286.3,  980.5,  408.8,  289.1,  449.9, 686.9,  465.4,  358.9,  506.9,  618.4,  599.4,  404.9,  815.8,
        455.3,  602.9,  546.3,  571.1,  747.2,  476.7,  666. , 1167. , 420.5,  857.6,  466.5,  992.1, 1007. ,  477.3,  538.7,  680.9, 485.6,  480.1, 1068. , 1320. ,  689.4,  595.9,  476.3, 1682. ,
        248.7,  272.5,  453.1,  366.5,  819.8,  731.3,  426. ,  680.7, 556.7,  658.8,  701.9,  391.2, 1052. , 1214. ,  493.1,  493.8, 257.8, 1841. ,  388.1,  571. ,  293.2,  221.3,  551.1,  468.5,
        594.2,  445.2,  422.9,  416.2,  575.5, 1299. ,  365.6, 1308. , 629.8,  406.4,  178.8,  170.4,  402.9,  656.4,  668.6,  538.4, 584.8,  573.2,  324.9,  320.8,  285.7,  361.6,  360.5,  378.4,
        507.9,  264. ,  514.3,  321.4,  311.7,  271.3,  657.1,  403.5, 600.4,  386. ,  716.9, 1347. , 1479. , 1261. ,  858.1, 1265. , 181. ]

malignant = [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1.]

In [ ]:
#Hitung nilai mean dari 'area' menggunakan python saja, kemudian menggunakan library yang telah di import

mean_python = sum(area) /len(area)
print(mean_python)

mean_statistics = statistics.mean(area)    #untuk python3.8
print(mean_statistics)

mean_numpy = np.average (area)
print(mean_numpy)

#Hitung nilai harmonic mean menggunakan scipy
harmonicmean = scipy.stats.hmean (area)
print(harmonicmean)

654.8891036906857
654.8891036906854
654.8891036906855
519.0704649372796


Expected output:


```
654.8891036906857 
654.8891036906854 
654.8891036906855 
519.0704649372796 
```




In [ ]:
#Hitung median dari 'area' menggunakan python saja dan numpy
n = len(area)
if n % 2 :
    median_python = sorted(area)[round(0.5*(n-1))]
else :
    area_ord, index = sorted(area), round(0.5*n)
    median_python = 0.5*(area_ord[index-1] + area_ord[index])
print(median_python)

median_numpy = np.median(area)
print(median_numpy)

551.1
551.1


Expected output:


```
551.1
551.1
```




In [ ]:
#Hitung Mode dari 'area' menggunakan scipy

mode_scipy = scipy.stats.mode(area)
print(mode_scipy)

ModeResult(mode=array([512.2]), count=array([3]))


Expected output:


```
ModeResult(mode=array([512.2]), count=array([3]))
```



In [ ]:
#Hitung variance dari 'area' menggunakan python saja, numpy, dan statistics

n = len(area)
variance_python = sum((item - mean_python)**2 for item in area) / (n-1)
print(variance_python)

variance_numpy = np.var(area,ddof=1)
print(variance_numpy)

variance_statistics = statistics.variance(area)
print(variance_statistics)

123843.55431768096
123843.55431768115
123843.55431768113


Expected output:


```
123843.55431768096
123843.55431768115
123843.55431768113
```



In [ ]:
#Hitung standar deviasi dari 'area' menggunakan python saja dan numpy

std_python = variance_python ** 0.5
print(std_python)

std_numpy = np.std(area, ddof=1)
print(std_numpy)

351.9141291816527
351.914129181653


Expected output:


```
351.9141291816527
351.914129181653
```



In [ ]:
#Hitung skewness dari 'area' menggunakan python saja dan scipy

skew_python = (sum((item - mean_python)**3 for item in area) * n / ((n-1) * (n-2) * std_python**3))
print(skew_python)

skew_scipy = scipy.stats.skew(area, bias = False)
print(skew_scipy)

1.6457321756240448
1.6457321756240424


Expected output:


```
1.6457321756240448
1.6457321756240424
```



In [ ]:
#Hitung percentile ke 66 dan 88 dari 'area' menggunakan numpy

percentile66 = np.percentile(area, 66)
print(percentile66)

percentile88 = np.percentile(area, 88)
print(percentile88)

665.8679999999999
1131.6799999999998


Expected output:


```
665.8679999999999
1131.6799999999998
```



In [ ]:
#Hitung range dari 'area' menggunakan python saja dan numpy

range_python = np.ptp(area)
print(range_python)

range_numpy = np.amax(area) - np.amin(area)
print(range_python)

2357.5
2357.5


Expected output:


```
2357.5
2357.5
```



In [ ]:
#Hitung covariance dari 'area' dan 'malignant' menggunakan python saja dan numpy

mean_x, mean_y = sum(area) / n, sum(malignant) / n
cov_python = (sum((area[k] - mean_x) * (malignant[k] - mean_y) for k in range (n))/(n-1))
print(cov_python)

cov_numpy = np.cov(area, malignant)
print(cov_numpy)

-120.73822186192733
[[ 1.23843554e+05 -1.20738222e+02]
 [-1.20738222e+02  2.34176589e-01]]


Expexted output:

```
-120.73822186192733
[[ 1.23843554e+05 -1.20738222e+02]
 [-1.20738222e+02  2.34176589e-01]]
```



In [ ]:
#Hitung correlation coefficient 'area' dan 'malignant' menggunakan python saja, numpy, dan scipy

mean_area = sum(area) / len(area) 
mean_malignant = sum(malignant) / len(malignant)
var_area = sum((item - mean_area)**2 for item in area) / (n-1)
var_malignant = sum((item - mean_malignant)**2 for item in malignant) / (n-1)
std_area, std_malignant = var_area ** 0.5, var_malignant ** 0.5
corr_python = cov_python / (std_area* std_malignant)
print(corr_python)

corr_numpy = np.corrcoef(area, malignant)
print(corr_numpy)

corr_scipy = scipy.stats.pearsonr(area, malignant)
print(corr_scipy[0])

-0.7089838365853909
[[ 1.         -0.70898384]
 [-0.70898384  1.        ]]
-0.708983836585389


Expected output:

```
-0.7089838365853909
[[ 1.         -0.70898384]
 [-0.70898384  1.        ]]
-0.70898383658539
```



In [ ]:
#Hitung p-value dari 'area' dan 'malignant' menggunakan scipy pearsonr dan linregress

p_pearsonr = scipy.stats.pearsonr(area, malignant)
print(p_pearsonr[1])

p_linregress = scipy.stats.linregress(area, malignant)
p = p_linregress.pvalue
print(p)

4.734564310308523e-88
4.7345643103105796e-88


Expected output:
```
4.734564310304486e-88
4.734564310310984e-88
```



Apa kesimpulan yang dapat diambil dari nilai koefisien korelasi antara 'area' dengan 'malignant'?

Jawab: cukup kuat dan berbanding terbalik



---



---

